const courses=[['Computer Science','ND / HND','School of Applied Sciences'],['Business Administration','ND / HND','School of Business'],['Accounting','ND / HND','School of Business'],['Electrical Engineering','ND / HND','School of Engineering'],['Computer Engineering','ND / HND','School of Engineering'],['Science Laboratory Technology','ND / HND','School of Applied Sciences']];
const roles={applicant:['Application','Upload Documents','Admission Status','Payment'],student:['Course Registration','Results','School Fees','Courses','Clearance','Accommodation'],staff:['Teaching Dashboard','Student Records','Results Entry','Course Materials'],admin:['Institution Dashboard','User Management','Academic Setup','Reports'],bursary:['Fees','Payments','Receipts','Financial Reports'],registry:['Admissions','Student Records','Academic Calendar','Documents'],hod:['Department Students','Courses','Lecturers','Results Approval'],lecturer:['Assigned Courses','Class List','Result Entry','Attendance'],ict:['System Users','Roles & Permissions','Audit Logs','System Settings']};
function renderCourses(list=courses){document.getElementById('courseList').innerHTML=list.map(c=>'<div class="course"><small>'+c[1]+'</small><h3>'+c[0]+'</h3><p>'+c[2]+'</p></div>').join('')}
function filterCourses(){const q=document.getElementById('courseSearch').value.toLowerCase();const level=document.getElementById('level').value;renderCourses(courses.filter(c=>c.join(' ').toLowerCase().includes(q)&&(level==='All Levels'||c[1].includes(level))))}
function openPortal(role='student'){document.getElementById('portalModal').classList.remove('hidden');document.getElementById('portalTitle').textContent=role.charAt(0).toUpperCase()+role.slice(1)+' Portal';document.getElementById('portalHint').textContent='Prototype login — production authentication will connect to the institutional backend.';document.getElementById('portalModules').innerHTML=(roles[role]||roles.student).map(x=>'<div>'+x+'</div>').join('')}
function closePortal(){document.getElementById('portalModal').classList.add('hidden')}
function loginDemo(){demoToast('Demo login accepted. Production version will authenticate against the backend.')}
function demoToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
function toggleMenu(){document.getElementById('navMenu').classList.toggle('open')}
function showSection(id){document.getElementById(id).scrollIntoView({behavior:'smooth'})}
renderCourses();